# Generated by Django 5.1.3 on 2024-11-14 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordereditem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_items', to='orders.order'),
        ),
    ]
